### ISSUE TITLE
Number of hearts after death

### ISSUE THREAD

**Issue by kellixon** [Terrails/StatsKeeper#19]
After death takes away 7 hearts with such parameters, instead of the planned one. All players in lan game.
MC 1.12.2. StatsKeeper 3.0.5.
`# Configuration file

basic {
    B:"Drop Experience"=false
    B:"Keep Experience"=true
}

health {
    # If using mods that mess with health system like ToughAsNails
    # make sure to disable theirs in config files before using this health system
    B:Enabled=true

     # items that will add max health on right click [default: [// toughasnails:lifeblood_crystal], [// cyclicmagic:heart_food], [// minecraft:wool;15 // metadata example, black wool], [minecraft:nether_star, 4 // amount example, 2 hearts instead of default 1]]
    S:"Health Items" <
		minecraft:diamond_block, 2
     >

    # Should the message for health removal be shown to the player
    B:"Health Message"=true
    I:"Health Reduction"=2
    I:"Max Health"=20
    I:"Min Health"=6
    B:"Min Health Start"=false

    # Reset the health of each player on config change
    B:"On Change Reset"=false
}

hunger {
    B:"Keep Hunger"=true
    B:"Keep Saturation"=true
    I:"Lowest Hunger"=6
    I:"Lowest Saturation"=2
    I:"No Appetite Time (Seconds)"=30
}

`

**Comment by Terrails** [comment]
What do you mean? I just tried it with 2 players in LAN with forge. I can't reproduce it, it still removes 1 heart like defined. Maybe I fixed it while working on the other issues, I'll release the version with all the fixes tomorrow, so just check it if it happens again then.

**Comment by kellixon** [comment]
After the death is 3 hearts, if after upgrading the problem persists I'll post a link to the video.

**Comment by kellixon** [comment]
https://youtu.be/kcW6qUFFurY - with version StatsKeeper 3.0.5 (TerraCore 1.13).
